name       : python-arrow
version    : 0.17.0
release    : 8
source     :
    - https://github.com/arrow-py/arrow/archive/0.17.0.tar.gz : 410171b5431586418246bec7dce5498657d8304b7ff45a270cfbbc12811206a2
homepage   : https://arrow.readthedocs.io
license    : Apache-2.0
component  : programming.python
summary    : Better dates and times for Python
description: |
    Arrow is a Python library that offers a sensible and human-friendly approach to creating, manipulating, formatting and converting dates, times and timestamps. It implements and updates the datetime type, plugging gaps in functionality and providing an intelligent module API that supports many common creation scenarios. Simply put, it helps you work with dates and times with fewer imports and a lot less code.
builddeps  :
    - python-dateutil
    - python-pytest-cov
    - python-pytest-mock
    - python-pytz
    - python-simplejson
rundeps    :
    - python-dateutil
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
