name       : python-arrow
version    : 0.10.0
release    : 2
source     :
    - https://pypi.python.org/packages/54/db/76459c4dd3561bbe682619a5c576ff30c42e37c2e01900ed30a501957150/arrow-0.10.0.tar.gz : 805906f09445afc1f0fc80187db8fe07670e3b25cdafa09b8d8ac264a8c0c722
license    : Apache-2.0
component  : programming.python
summary    : Better dates and times for Python
description: |
    Better dates and times for Python
rundeps    :
    - python-dateutil
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
