name       : python-arrow
version    : 0.15.4
release    : 4
source     :
    - https://files.pythonhosted.org/packages/a2/58/fd486f60594fe51afd1d2f2f0e8a80832d5b3d66c100caef24dadcdc95d7/arrow-0.15.4.tar.gz : e1a318a4c0b787833ae46302c02488b6eeef413c6a13324b3261ad320f21ec1e
license    : Apache-2.0
component  : programming.python
summary    : Better dates and times for Python
description: |
    Better dates and times for Python
rundeps    :
    - python-dateutil
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
